### ISSUE TITLE
Repeated styles

### ISSUE THREAD

**Issue by ghost** [cdstout1106/prj-rev-bwfs-dasmoto#3]
https://github.com/cdstout1106/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/resources/css/style.css#L10-L32

These three rules are basically identical. Try to extract them into a single rule with multiple selectors, and just use individual rules for the styles that are not shared (like the background-color).

You should also definitely not specify the font in every single rule. Use the same refactor.

```css
h1, h2, h3, p, span {
  font-family: Helvetica;
}
```
